import type { Metadata } from "next";
import { Geist, Geist_Mono, Lato, Poppins } from "next/font/google";
import localFont from 'next/font/local';
import "@/styles/globals.css";
import "@/styles/custom.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: "400"
});

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["400", "100", "300", "700", "900"]
});

const peaceSans = localFont({
  src: '../public/fonts/peace-sans.otf',
  display: 'swap',
  variable: '--font-peace-sans',
});

const japanRamen = localFont({
  src: '../public/fonts/japan-ramen.otf',
  display: 'swap',
  variable: '--font-japan-ramen',
});

const progressPersonalUse = localFont({
  src: '../public/fonts/progress-personal-use.ttf',
  display: 'swap',
  variable: '--font-progress-personal-use',
});

export const metadata: Metadata = {
  title: "Webxora",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable} 
          ${geistMono.variable} 
          ${peaceSans.variable} 
          ${japanRamen.variable} 
          ${lato.variable}
          ${poppins.variable} 
          ${progressPersonalUse.variable} 
          antialiased`
        }
      >
        {children}
      </body>
    </html>
  );
}
